### ISSUE TITLE
Options for config file

### ISSUE THREAD

**Issue by shortwavedave** [astarte-platform/astartectl#75]
Where can I find the configuration options for the config file?  Trying to replace this command with a config

`astartectl realm-management triggers install my_trigger.json --realm-management-url http://localhost:4000/ -r test -k test_private.pem`

so options like the realm-management-url, housekeeping-url, etc.

**Comment by rbino** [comment]
Hi @shortwavedave, there's a minimal config example [in the README](https://github.com/astarte-platform/astartectl#configuration).

Since you are using astartectl for local development, instead of using
```yaml
url: https://<your API base url>
```
you have to provide the URL to the different APIs, since they can't be deduced by the base url, so your complete config would be
```yaml
housekeeping:
  url: http://localhost:4001
  key: <path-to-your-housekeeping_private.pem>
realm:
  key: <path-to-your-test_private.pem>
  name: test
realm-management:
  url: http://localhost:4000
pairing:
  url: http://localhost:4003
appengine:
  url: http://localhost:4002
```
